### ISSUE TITLE
Bibliotheken tflite in Standard PlatformIO Projekt

### ISSUE THREAD

**Issue by Kuhnok** [jomjol/ctmake-KI-ESP32-Teil3#1]
Hallo, 

wie kann ich die tflite Bibliotheken zu einem Standard PlatformIO Projekt hinzufügen? 
 
Wenn ich jomjol_tfliteclass und tflite-lib in den lib Ordner mache und die dann in der platformio.ini bekannt mache, sagt er immer, dass er die flatbuffers.h nicht finden kann.

**Comment by jomjol** [comment]
Hallo,
  
du musst die Files nicht in den `lib`-Ordner kopieren, sondern in dem `components` Ordner belassen und trotzdem per `lib-deps` in der `platformio.ini` einbinden.
  
 Schau dir mal dieses Projekt an: https://github.com/jomjol/AI-on-the-edge-device/tree/master/code

Dort werden ähnliche Bibliotheken (und noch viel mehr) verwendet und das läßt sich per PlatformIO einbinden - siehe auch `platfomrio.ini`.

Gruß,
  jomjol

**Comment by jomjol** [comment]
Problem scheint gelöst --> Schließe den Issue
